version: '3.7'

services:
  phoenix:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: .
         dockerfile: Dockerfile
      environment:
        # Variables to connect to our Postgres server.
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DATABASE: elixir_amqp_repo
         POSTGRES_PORT: 5432
         DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres 
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '4000:4000'
      depends_on:
         # The DB container needs to be started before we start this container.
         - rabbitmq
         - postgres
         - redis
      volumes:
        - .:/app

  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
    volumes:
      - ./docker/rabbitmq/plugins:/etc/rabbitmq/enabled_plugins
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    image: postgres:12-alpine
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql@12/data
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: elixir_amqp_repo

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data: {}
  rabbitmq-data: {}
  redis-data: {}